### PR TITLE
Hey added

### PR DESCRIPTION
**Pull request by vivek-ncompass**
I have added  hey file to your repo to complete all the salutations

### CODE REVIEW

**Comment by ankitk-ncompass** [comment]
Change the name of file.

**Comment by vivek-ncompass** [comment]
are you sure ?

**Comment by ankitk-ncompass** [comment]
100%

**Comment by vivek-ncompass** [comment]
Dear Ankit,
I have changed the file name pls merge it out now..................

**Comment by ankitk-ncompass** [comment]
ok done

**Pull request merged**
